import pandas as pd
"""
df_diet = pd.read_csv('../preprocessed/1999-2000Diet_DRXTOT-ok.csv')
#df_msx = pd.read_csv('../preprocessed/1999-2000MuscleStrength_MSX-ok.csv')
df_all = pd.read_csv('../preprocessed/1999-2000MuscleMassDXA_All Years-ok.csv')
df_diabetes = pd.read_csv('../preprocessed/1999-2000Diabetes-ok.csv')
df_demo = pd.read_csv('../preprocessed/1999-2000Demography_DEMO-ok.csv')
#df_cdq = pd.read_csv('../preprocessed/1999-2000Cardiovascular_CDQHealth-ok.csv')
#df_dep = pd.read_csv('../preprocessed/1999-2000Depression-ok.csv')
df_med = pd.read_csv('../preprocessed/1999-2000MedicalConditions.csv')
df_phy = pd.read_csv('../preprocessed/1999-2000PhysicalActivity.csv')
print(df_diet.shape)
#print(df_msx.shape)
print(df_all.shape)
print(df_diabetes.shape)
print(df_demo.shape)
#print(df_cdq.shape)
#print(df_dep.shape)
print(df_med.shape)
print(df_phy.shape)
df = pd.concat([df_diet, df_all, df_diabetes, df_demo, df_med, df_phy], axis=1, join='inner')
df['Total_BMC'] = df['DXDRLLE'] + df['DXDRALE'] + df['DXDLLLE'] + df['DXDLALE']
#df['Arm_BMC'] = df['DXDRALE'] + df['DXDLALE']
#df['Leg_BMC'] = df['DXDRLLE'] + df['DXDLLLE']
df = df.drop(['DXDRLLE', 'DXDRALE', 'DXDLLLE', 'DXDLALE'], axis=1)
print(df.shape)
df.to_csv('../raw_data/1999-2000rawdata.csv', index = False)
df = pd.read_csv('../raw_data/1999-2000rawdata.csv').fillna(0)
df.to_csv('../raw_data/1999-2000rawdata_fillna0.csv', index = False)
"""
df_demo = pd.read_csv('../preprocessed/1999-2000Demography_DEMO-ok.csv').fillna(0)
print(df_demo.shape)
df_diet = pd.read_csv('../new_data/1999-2000Diet_DRXTOT.csv').fillna(0)
print(df_diet.shape)
df_all = pd.read_csv('../preprocessed/1999-2000MuscleMassDXA_All Years-ok.csv').fillna(0)
print(df_all.shape)
df_diabetes = pd.read_csv('../preprocessed/1999-2000Diabetes-ok.csv').fillna(0)
print(df_diabetes.shape)
df_med = pd.read_csv('../new_data/1999-2000MedicalConditions.csv').fillna(0)
print(df_med.shape)
df_phy = pd.read_csv('../new_data/1999-2000PhysicalActivity.csv').fillna(0)
print(df_phy.shape)
#df_cdq = pd.read_csv('../preprocessed/1999-2000Cardiovascular_CDQHealth-ok.csv')
#df_dep = pd.read_csv('../preprocessed/1999-2000Depression-ok.csv')
#df_msx = pd.read_csv('../preprocessed/1999-2000MuscleStrength_MSX-ok.csv')
#print(df_cdq.shape)
#print(df_dep.shape)
#print(df_msx.shape)
df = pd.concat([df_diet, df_all, df_diabetes, df_demo, df_med, df_phy], axis=1, join='inner')
df = df.drop('SEQN', axis=1)
print(df.shape)
df.to_csv('../raw_data/1999-2000rawdata_0505_noSEQN.csv', index = False)